In [5]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os

In [13]:
df_gt= pd.read_csv("../data/raw/ISIC_2019_Training_GroundTruth.csv")
df_meta= pd.read_csv("../data/raw/ISIC_2019_Training_Metadata.csv")
df = df_meta.merge(df_gt, on="image", how="inner")
df

,image,age_approx,anatom_site_general,lesion_id,sex,MEL,NV,BCC,AK,BKL,DF,VASC,SCC,UNK
0,ISIC_0000000,55.0,anterior torso,NaN,female,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ISIC_0000001,30.0,anterior torso,NaN,female,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ISIC_0000002,60.0,upper extremity,NaN,female,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ISIC_0000003,30.0,upper extremity,NaN,male,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ISIC_0000004,80.0,posterior torso,NaN,male,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25326,ISIC_0073247,85.0,head/neck,BCN_0003925,female,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
25327,ISIC_0073248,65.0,anterior torso,BCN_0001819,male,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
25328,ISIC_0073249,70.0,lower extremity,BCN_0001085,male,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25329,ISIC_0073251,55.0,palms/soles,BCN_0002083,female,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25330,ISIC_0073254,50.0,upper extremity,BCN_0001079,male,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25331 entries, 0 to 25330
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   image                25331 non-null  object
 1   age_approx           24894 non-null  float64
 2   anatom_site_general  22700 non-null  object
 3   lesion_id            23247 non-null  object
 4   sex                  24947 non-null  object
 5   MEL                  25331 non-null  float64
 6   NV                   25331 non-null  float64
 7   BCC                  25331 non-null  float64
 8   AK                   25331 non-null  float64
 9   BKL                  25331 non-null  float64
 10  DF                   25331 non-null  float64
 11  VASC                 25331 non-null  float64
 12  SCC                  25331 non-null  float64
 13  UNK                  25331 non-null  float64
dtypes: float64(10), object(4)
memory usage: 2.7+ MB

- Categorical (nominal): anatom_site_general, sex
- Identifier: image, lesion_id
- Numerical (continuous): age_approx
- Target Variables (one-hot encoded): MEL, NV, BCC, AK, BKL, DF, VASC, SCC, UNK
- Blank or Null:
    • age_approx: 437 missing values
    • anatom_site_general: 2,631 missing values
    • lesion_id: 2,084 missing values
    • sex: 384 missing values

In [15]:
df.describe()

,age_approx,MEL,NV,BCC,AK,BKL,DF,VASC,SCC,UNK
count,24894.000000,25331.000000,25331.000000,25331.000000,25331.000000,25331.000000,25331.000000,25331.000000,25331.000000,25331.0
mean,54.028481,0.178516,0.508270,0.131183,0.034227,0.103588,0.009435,0.009988,0.024792,0.0
std,18.130971,0.382954,0.499941,0.337607,0.181815,0.304732,0.096677,0.099440,0.155493,0.0
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
25%,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
50%,55.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
75%,70.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
max,85.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0

In [16]:
df.describe(include="object")

               image anatom_site_general    lesion_id    sex
count          25331               22700        23247  24947
unique         25331                   8        11847      2
top     ISIC_0000000      anterior torso  BCN_0001728   male
freq               1                6915           31  13286